### ISSUE TITLE
No results in TreeDropdownField on successive use

### ISSUE THREAD

**Issue by nglasl** [silverstripe/silverstripe-cms#2112]
When you're using the tree dropdown field, you'll notice it does a little AJAX request (look at the network tab) when you get to a certain depth. This is fine, until you go to insert another page link. After this tree dropdown field initialises, it will show "no results found". This is fixed by hard refreshing the page.

If you review the network tab, the AJAX requests all come back with the correct data. Therefore this leads me to believe there's an issue with the JS that's collating the results.

This was tested and confirmed in both 4.0.1 and 4.0.3.

# PRs:

 - [ ] https://github.com/silverstripe/silverstripe-admin/pull/476

**Comment by chillu** [comment]
Marking as `impact/high` since it's very common to insert more than one link to another page in the same "browser session"

**Comment by tractorcow** [comment]
Looking at this now.

**Comment by tractorcow** [comment]
I've tested this with both 4.0.3 stable and 4.0.x-dev branches and I can't reproduce this issue @nglasl.

Are you sure you aren't just looking at the bottom level and need to press "back" to go up one level?

E.g. when viewing a page 3 levels deep.

![image](https://user-images.githubusercontent.com/936064/36953379-16221e70-207f-11e8-96ee-174ecb51011d.png)

**Comment by tractorcow** [comment]
I also can't reproduce it in 4.0.1.

**Comment by nglasl** [comment]
Having a look at this again right now. I will see if I can grab some screenshots and exact steps to replicate.

**Comment by nglasl** [comment]
Okay, I'm having trouble reproducing this too. I'm not getting the AJAX request (which is what caused the issue). This is likely because I don't have the same volume of pages when using a fresh 4.X instance.

I've just imported a large database into my fresh 4.X instance, and I can now reproduce the problem again. Using this database, the AJAX request triggers when I go down exactly three page levels. So for example:

```
Home
  > Test 1
    > Test 2
      > Test 3 (AJAX request now triggers)
```

When you reproduce the above, close the pop-up and try adding another page link. This is what you'll see:

![1](https://user-images.githubusercontent.com/3703500/37005263-a0e69ad8-2127-11e8-8df8-27cba3cbc598.png)

**Comment by nglasl** [comment]
This is what the network tab looks like as you go down that third page level.

![2](https://user-images.githubusercontent.com/3703500/37005512-75dff630-2128-11e8-8142-7fefc01f84b9.png)

**Comment by nglasl** [comment]
Hi @tractorcow, any luck with this one?

**Comment by nglasl** [comment]
Hey @tractorcow, I don't suppose this one is on your list any time soon? I started looking at what's involved, and I'm going to need to get **webpack** up and running.

**Comment by sam-law** [comment]
Hey all, I have the same issue, that I can replicate consistently.

1) Go into the editor panel where a sitetree shows and exists, displays the site tree correctly
![2018-03-22 17_23_54-silverstripe - edit page](https://user-images.githubusercontent.com/684902/37751176-d46bda64-2df5-11e8-8521-e274b170c4c3.png)

2) Navigate down and select a target page
![2018-03-22 17_24_44-silverstripe - edit page](https://user-images.githubusercontent.com/684902/37751196-f6f3f670-2df5-11e8-9469-43faec3e59be.png)

3) Save / apply changes

4) Go to create a new link, and the site tree is empty to start
![2018-03-22 17_25_31-silverstripe - edit page](https://user-images.githubusercontent.com/684902/37751214-100aa2bc-2df6-11e8-93f5-0799d7fbc843.png)

5) Click it open and it shows no results found - clicking X or similar does nothing (as noted above, a network requests shows the site tree in chrome, so items were successfully retrieved).
![2018-03-22 17_25_52-silverstripe - edit page](https://user-images.githubusercontent.com/684902/37751228-1ef40b92-2df6-11e8-9766-0d812fa4ad7f.png)

6) Enter something as a search query where no results are found (see the animation for search ocurring)
![2018-03-22 17_27_02-silverstripe - edit page](https://user-images.githubusercontent.com/684902/37751261-468dab40-2df6-11e8-9327-eda3cf14378d.png)

7) Press X to remove search, and see animation for refresh, see that it still lists no results
![2018-03-22 17_28_02-silverstripe - edit page](https://user-images.githubusercontent.com/684902/37751290-725003e0-2df6-11e8-9489-25986584ac44.png)

8) Try a search query where a page will be returned correctly
![2018-03-22 17_29_33-silverstripe - edit page](https://user-images.githubusercontent.com/684902/37751312-9d932a1e-2df6-11e8-89af-b941f93301d9.png)

9) You can now clear the search and you will get the site-tree correctly at the level you selected previously
![2018-03-22 17_30_13-silverstripe - edit page](https://user-images.githubusercontent.com/684902/37751323-b43d2fe4-2df6-11e8-85e1-cfc939db4dda.png)

As noted, if you reload the entire page, this also corrects the issue.

**Comment by nglasl** [comment]
Okay, so I've looked into this one and found a temporary solution. I'll explain and then add some more details below on why this is temporary.

# The problem

When using tree drop down fields within a WYSIWYG (the simplest location to replicate the issue), it's possible for the tree drop down field to enter a state where you can no longer make a selection. This forces the user to hard refresh the page if they want to continue adding content.

# My solution

I started debugging this one to get a better understanding of what's happening, and basically what's happening is that..

a) Assuming the following structure, the first tree drop down field that's used has it's "value" and "visible" **props** set, so for example, you've selected **Page 4** which is then mapped to "value". Since you've drilled down into the tree to make this selection, the "visible" was **Page 3** when this selection was made.

```
Page 1
    Page 2
        Page 3
            -- Page 4 --
```

While there is an AJAX request made to first populate the tree drop down field, as you go further down into the site tree there's a subsequent AJAX request made to grab the next part of the site tree. This is perfectly fine for now, and can be illustrated above with the -- notation, where **Page 4** is loaded after drilling down further into the tree.

b) Now, if you close this window and try to add another page link, the next tree drop down field is initialised.  This is where you'll notice that opening the field shows "no results found", and nothing else to interact with. **The key thing to note here, is that the new tree drop down field inherits the props from the previous tree drop down field.** This is because they're stored in the **global store** (from what I can see).

So what's happening is that your new tree drop down field has the above structure loaded in (excluding **Page 4**). However, it thinks that **Page 4** is selected, and that everything under **Page 3** should be visible. But hang on, that doesn't really work. Hence why we get "no results found".

c) Now to the temporary solution that I was talking about.

https://github.com/silverstripe/silverstripe-admin/blob/1.0/client/src/components/TreeDropdownField/TreeDropdownField.js#L63

The section basically needs to be replaced by..

```
this.props.actions.treeDropdownField.setVisible(this.props.id, []);
```

So whenever the tree drop down is initialised (adding a new page link, or editing an existing page link), the "visible" will always start back at the site tree root. While this does solve the above issue, you now lose the selected page context when editing an existing page link. I also found that it's a little glitchy, in that you'll have the context appear, and then replaced with the site tree root (rather than just saying "loading" until the site tree root is ready to appear). Hence why I see this solution as temporary.

# The solution

To properly fix this, I propose that we rewrite the tree drop down field component such that a brand new component always starts with an empty "value" and "visible" rather than depending on global state. I'm not sure on the effort involved here because this is new territory for me, but I'm keen to hear your thoughts.

**Comment by tractorcow** [comment]
Ok, so the long and short of it is that if a particular tree node is "too" deep in the tree, then it won't be loaded properly due to incremental loading of the tree. I.e. if the cut-off point is before the selected node.

Possibly a fix here is to ensure that the "selected" node is passed as marked when requesting nodes via ajax. I.e. forcing it (and it's path) to be returned via the ajax request.

We can easily replicate this issue now by reducing the cut-off threshold to something tiny (e.g. 2 nodes) and a simple site-tree with a depth of 3.

**Comment by nglasl** [comment]
While that is a solution, is there a particular reason that every tree drop down field shares the "visible" state? As in, should what I select in tree drop down field x be what is automatically displayed when I open tree drop down field y? This seems like incorrect behaviour to me.

**Comment by tractorcow** [comment]
It's only each field on the same form; Essentially we are treating the "insert link" form (for example) as one form that's opened and closed, when may we should treat each activation as a separate form.

On the other hand, it should not be broken either way should it?

**Comment by nglasl** [comment]
Yeah, it feels like each new activation should be a separate form. As in, if I use the "insert link", and then decide that I want to edit that same link, it's still technically the same form (so it should maintain its state). However, adding a new link with "insert link" should instantiate a separate form. That's how it *feels* like it should work, but I'm not saying that change is going to be an easy or possible task. Correct, either way it should be working.

**Comment by robbieaverill** [comment]
Similar sounding issue (while skim reading) has been raised as https://github.com/silverstripe/silverstripe-admin/issues/472 with accompanying patch fix

**Comment by tractorcow** [comment]
PR at https://github.com/silverstripe/silverstripe-admin/pull/476

**Comment by Juanitou** [comment]
Hi!

I still have this issue in the following case:

- The TreeDropDownField has Folder::class as source object.
- I apply setTreeBaseID to the tree to set the base folder. In other words: I can only navigate a Folder hierarchy if BaseID is 0 (tested with $tree->setTreeBaseID(0).

Can somebody try to reproduce?

Thanks in advance

**Comment by Juanitou** [comment]
@tractorcow Sure: #2205
